name: rtmp_broadcaster_mux
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.1
  rtmp_broadcaster: ^2.2.6
  wakelock: ^0.6.2

dev_dependencies:
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo_app.jpg"
  min_sdk_version: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
